name: Dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: appt install dependency
      run: |
         sudo apt-get update
          sudo apt-get -y install valgrind
          sudo apt-get -y install libcuntil-dog libcunit1-dev
    - name: Dynamic Analysis
      run: make Dynamic_Analysis -C 3_Implementation
 
